name: build in win linux apk

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Package Windows application
        run: npm run build

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: Funkin.mit-enine-windows-x64
          path: dist/
          if-no-files-found: error
          compression-level: 6

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Package Linux application
        run: npm run build:linux

      - name: Upload Linux application
        uses: actions/upload-artifact@v4
        with:
          name: Funkin.mit-engine-linux-x64
          path: dist/Funkin.mit-engine-x64/
          if-no-files-found: error
          compression-level: 6
